language: ruby
rvm:
  - 2.1.2
before_install:
  - gem install bundler
install:
  - bundle install
addons:
  code_climate:
    repo_token: 83120d621f4a9ca876fd2069a8213b93d1a6f516276159987921972b95871a07
notifications:
  email:
    recipients:
      - icaro.seara@email.com
    on_failure: change
    on_success: never